var searchData=
[
  ['serializerfromptr_7587',['SerializerFromPtr',['../classnn_1_1sl_1_1details_1_1SerializerFromPtr.html',1,'nn::sl::details']]],
  ['serializerfromptr_3c_20nn_3a_3asl_3a_3akillernotification_20_3e_7588',['SerializerFromPtr&lt; nn::sl::KillerNotification &gt;',['../classnn_1_1sl_1_1details_1_1SerializerFromPtr.html',1,'nn::sl::details']]],
  ['serializerfromptr_3c_20nn_3a_3asl_3a_3atitleinfo_20_3e_7589',['SerializerFromPtr&lt; nn::sl::TitleInfo &gt;',['../classnn_1_1sl_1_1details_1_1SerializerFromPtr.html',1,'nn::sl::details']]],
  ['serializerfromptr_3c_20ostime_20_3e_7590',['SerializerFromPtr&lt; OSTime &gt;',['../classnn_1_1sl_1_1details_1_1SerializerFromPtr.html',1,'nn::sl::details']]],
  ['servent_7591',['servent',['../netdb_8h.html#structservent',1,'']]],
  ['setting_7592',['Setting',['../namespacenn_1_1sl.html#structnn_1_1sl_1_1Setting',1,'nn::sl']]],
  ['setting_2ecaffeine_7593',['Setting.caffeine',['../namespacenn_1_1sl.html#structnn_1_1sl_1_1Setting_8caffeine',1,'nn::sl']]],
  ['settingaccessorfromptr_7594',['SettingAccessorFromPtr',['../classnn_1_1sl_1_1details_1_1SettingAccessorFromPtr.html',1,'nn::sl::details']]],
  ['smdctrltable_7595',['SmdCtrlTable',['../group__coreinit__smd.html#structSmdCtrlTable',1,'']]],
  ['smdelement_7596',['SmdElement',['../group__coreinit__smd.html#structSmdElement',1,'']]],
  ['smdelement_2e_5f_5funnamed9_5f_5f_7597',['SmdElement.__unnamed9__',['../group__coreinit__smd.html#unionSmdElement_8____unnamed9____',1,'']]],
  ['smdinterface_7598',['SmdInterface',['../group__coreinit__smd.html#structSmdInterface',1,'']]],
  ['smdppc_7599',['SmdPpc',['../group__coreinit__smd.html#structSmdPpc',1,'']]],
  ['smdppcctrltablevectors_7600',['SmdPpcCtrlTableVectors',['../group__coreinit__smd.html#structSmdPpcCtrlTableVectors',1,'']]],
  ['smdreceivedata_7601',['SmdReceiveData',['../group__coreinit__smd.html#structSmdReceiveData',1,'']]],
  ['smdreceivedata_2e_5f_5funnamed11_5f_5f_7602',['SmdReceiveData.__unnamed11__',['../group__coreinit__smd.html#unionSmdReceiveData_8____unnamed11____',1,'']]],
  ['smdsimplebufpool_7603',['SmdSimpleBufPool',['../group__coreinit__smd.html#structSmdSimpleBufPool',1,'']]],
  ['smdvector_7604',['SmdVector',['../group__coreinit__smd.html#structSmdVector',1,'']]],
  ['smdvectorspec_7605',['SmdVectorSpec',['../group__coreinit__smd.html#structSmdVectorSpec',1,'']]],
  ['sockaddr_7606',['sockaddr',['../sys_2socket_8h.html#structsockaddr',1,'']]],
  ['sockaddr_5fin_7607',['sockaddr_in',['../in_8h.html#structsockaddr__in',1,'']]],
  ['sockaddr_5fstorage_7608',['sockaddr_storage',['../sys_2socket_8h.html#structsockaddr__storage',1,'']]],
  ['storageinfo_7609',['StorageInfo',['../namespacenn_1_1spm.html#structnn_1_1spm_1_1StorageInfo',1,'nn::spm']]],
  ['storagelistitem_7610',['StorageListItem',['../namespacenn_1_1spm.html#structnn_1_1spm_1_1StorageListItem',1,'nn::spm']]],
  ['sysappbrowserargs_7611',['SysAppBrowserArgs',['../group__sysapp__switch.html#structSysAppBrowserArgs',1,'']]],
  ['sysappbrowserargswithcallback_7612',['SysAppBrowserArgsWithCallback',['../group__sysapp__switch.html#structSysAppBrowserArgsWithCallback',1,'']]],
  ['sysappemanualargs_7613',['SysAppEManualArgs',['../group__sysapp__switch.html#structSysAppEManualArgs',1,'']]],
  ['sysappeshopargs_7614',['SysAppEShopArgs',['../group__sysapp__switch.html#structSysAppEShopArgs',1,'']]],
  ['sysappmiimakerargs_7615',['SysAppMiiMakerArgs',['../group__sysapp__launch.html#structSysAppMiiMakerArgs',1,'']]],
  ['sysappnotificationargs_7616',['SysAppNotificationArgs',['../group__sysapp__launch.html#structSysAppNotificationArgs',1,'']]],
  ['sysappparentalargs_7617',['SysAppParentalArgs',['../group__sysapp__launch.html#structSysAppParentalArgs',1,'']]],
  ['sysappsettingsargs_7618',['SysAppSettingsArgs',['../group__sysapp__launch.html#structSysAppSettingsArgs',1,'']]],
  ['sysargdatablock_7619',['SYSArgDataBlock',['../group__sysapp__args.html#structSYSArgDataBlock',1,'']]],
  ['sysargdatablock_2e_5f_5funnamed47_5f_5f_7620',['SYSArgDataBlock.__unnamed47__',['../group__sysapp__args.html#unionSYSArgDataBlock_8____unnamed47____',1,'']]],
  ['sysargdatablock_2e_5f_5funnamed47_5f_5f_2edata_7621',['SYSArgDataBlock.__unnamed47__.data',['../group__sysapp__args.html#structSYSArgDataBlock_8____unnamed47_____8data',1,'']]],
  ['sysargdatablock_2e_5f_5funnamed47_5f_5f_2estring_7622',['SYSArgDataBlock.__unnamed47__.string',['../group__sysapp__args.html#structSYSArgDataBlock_8____unnamed47_____8string',1,'']]],
  ['syscallerinfo_7623',['SYSCallerInfo',['../group__sysapp__args.html#structSYSCallerInfo',1,'']]],
  ['sysdeserializearg_7624',['SYSDeserializeArg',['../group__sysapp__args.html#structSYSDeserializeArg',1,'']]],
  ['sysstandardargs_7625',['SYSStandardArgs',['../group__sysapp__args.html#structSYSStandardArgs',1,'']]],
  ['sysstandardargsin_7626',['SYSStandardArgsIn',['../group__sysapp__args.html#structSYSStandardArgsIn',1,'']]],
  ['sysstandardargsout_7627',['SYSStandardArgsOut',['../group__sysapp__args.html#structSYSStandardArgsOut',1,'']]]
];
